-- Generado por Oracle SQL Developer Data Modeler 4.1.5.907
--   en:        2017-10-05 00:56:17 CST
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE DESPACHO
  (
    COD_DESPACHO         INTEGER NOT NULL ,
    COD_PAQUETE          INTEGER NOT NULL ,
    FECHA_DESPACHO       DATE ,
    NUMERO_HOJA_DESPACHO INTEGER ,
    USUARIO_DESPACHO     VARCHAR2 (100) ,
    ID_ESTATUS_DESPACHO  INTEGER
  ) ;
ALTER TABLE DESPACHO ADD CONSTRAINT DESPACHO_PK PRIMARY KEY ( COD_DESPACHO ) ;


CREATE TABLE DIRECCIONES_ENTREGAS
  (
    DIRECCION_ENTREGA INTEGER NOT NULL ,
    CALLE             VARCHAR2 (100) ,
    AVENIDA           VARCHAR2 (100) ,
    NO_VIVIENDA       VARCHAR2 (10) NOT NULL ,
    ZONA              INTEGER NOT NULL ,
    PROVINCIA         VARCHAR2 (100) ,
    MUNICIPIO         VARCHAR2 (100)
    --  ERROR: VARCHAR2 size not specified
    NOT NULL ,
    PAIS                VARCHAR2 (100) NOT NULL ,
    COD_ENTREGA         INTEGER NOT NULL ,
    ENTREGA_COD_ENTREGA INTEGER NOT NULL
  ) ;
ALTER TABLE DIRECCIONES_ENTREGAS ADD CONSTRAINT DIRECCIONES_ENTREGAS_PK PRIMARY KEY ( DIRECCION_ENTREGA ) ;


CREATE TABLE EMPRESA_TRACKING
  (
    COD_EMPRESA_TRACKING    INTEGER NOT NULL ,
    NOMBRE_EMPRESA_TRACKING VARCHAR2 (200) ,
    TRACKING_COD_TRACKING   INTEGER NOT NULL
  ) ;
ALTER TABLE EMPRESA_TRACKING ADD CONSTRAINT EMPRESA_TRACKING_PK PRIMARY KEY ( COD_EMPRESA_TRACKING ) ;


CREATE TABLE ENTREGA
  (
    COD_ENTREGA                 INTEGER NOT NULL ,
    NUMERO_HOJA_DESPACHO        INTEGER NOT NULL ,
    FECHA_ENTREGA               DATE ,
    DIRECCION_ENTREGA           VARCHAR2 (200) NOT NULL ,
    NOMBRE_ENTREGA              VARCHAR2 (200) NOT NULL ,
    ESTATUS_ENTREGA             INTEGER NOT NULL ,
    USUARIO_ENTREGA             VARCHAR2 (200) NOT NULL ,
    ENVIOS_NUMERO_HOJA_DESPACHO INTEGER NOT NULL ,
    ENVIOS_COD_ENTREGA          INTEGER NOT NULL
  ) ;
ALTER TABLE ENTREGA ADD CONSTRAINT ENTREGA_PK PRIMARY KEY ( COD_ENTREGA ) ;


CREATE TABLE ENVIOS
  (
    NUMERO_HOJA_DESPACHO  INTEGER NOT NULL ,
    FECHA_ENVIO           DATE NOT NULL ,
    ID_UNIDAD             INTEGER NOT NULL ,
    COD_TRACKING          INTEGER ,
    DESCRIPCION           VARCHAR2 (500) NOT NULL ,
    USUARIO_ENVIO         VARCHAR2 (100) NOT NULL ,
    COD_ENTREGA           INTEGER NOT NULL ,
    COD_PAQUETE           INTEGER NOT NULL ,
    DESPACHO_COD_DESPACHO INTEGER NOT NULL ,
    NOMBRE_ENVIA          VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE ENVIOS ADD CONSTRAINT ENVIOS_PK PRIMARY KEY ( NUMERO_HOJA_DESPACHO, COD_ENTREGA ) ;


CREATE TABLE ESTATUS_DESPACHO
  (
    ID_ESTATUS_DESPACHO     INTEGER NOT NULL ,
    DESCRI_ESTATUS_DESPACHO VARCHAR2 (10) ,
    DESPACHO_COD_DESPACHO   INTEGER NOT NULL
  ) ;
ALTER TABLE ESTATUS_DESPACHO ADD CONSTRAINT ESTATUS_DESPACHO_PK PRIMARY KEY ( ID_ESTATUS_DESPACHO ) ;


CREATE TABLE ESTATUS_ENTREGA
  (
    ESTATUS_ENTREGA        INTEGER NOT NULL ,
    DESCRI_ESTATUS_ENTREGA VARCHAR2 (10) NOT NULL ,
    ENTREGA_COD_ENTREGA    INTEGER NOT NULL
  ) ;
ALTER TABLE ESTATUS_ENTREGA ADD CONSTRAINT ESTATUS_ENTREGA_PK PRIMARY KEY ( ESTATUS_ENTREGA ) ;


CREATE TABLE ESTATUS_MENSAJERO
  (
    ESTATUS_MENSAJERO        INTEGER NOT NULL ,
    DESCRI_ESTATUS_MENSAJERO VARCHAR2 (20) NOT NULL ,
    MENSAJEROS_COD_MENSAJERO INTEGER NOT NULL
  ) ;
ALTER TABLE ESTATUS_MENSAJERO ADD CONSTRAINT ESTATUS_MENSAJERO_PK PRIMARY KEY ( ESTATUS_MENSAJERO ) ;


CREATE TABLE ESTATUS_PAQUETE
  (
    ESTATUS_PAQUETE        INTEGER NOT NULL ,
    DESCRI_ESTATUS_PAQUETE VARCHAR2 (20) NOT NULL ,
    PAQUETE_COD_PAQUETE    INTEGER NOT NULL
  ) ;
ALTER TABLE ESTATUS_PAQUETE ADD CONSTRAINT ESTATUS_PAQUETE_PK PRIMARY KEY ( ESTATUS_PAQUETE ) ;


CREATE TABLE ESTATUS_TRACKING
  (
    COD_ESTATUS_TRACKING    INTEGER NOT NULL ,
    DESCRI_ESTATUS_TRACKING VARCHAR2 (10) NOT NULL ,
    TRACKING_COD_TRACKING   INTEGER NOT NULL
  ) ;
ALTER TABLE ESTATUS_TRACKING ADD CONSTRAINT ESTATUS_TRACKING_PK PRIMARY KEY ( COD_ESTATUS_TRACKING ) ;


CREATE TABLE ESTATUS_VEHICULO
  (
    ESTATUS_VEHICULO        INTEGER NOT NULL ,
    DESCRI_ESTATUS_VEHICULO VARCHAR2 (50) NOT NULL ,
    VEHICULO_COD_VEHICULO   INTEGER NOT NULL
  ) ;
ALTER TABLE ESTATUS_VEHICULO ADD CONSTRAINT ESTATUS_VEHICULO_PK PRIMARY KEY ( ESTATUS_VEHICULO ) ;


CREATE TABLE MENSAJEROS
  (
    COD_MENSAJERO              INTEGER NOT NULL ,
    PRIMER_NOMBRE_MENSAJERO    VARCHAR2 (50) NOT NULL ,
    SEGUNDO_NOMBRE_MENSAJERO   VARCHAR2 (50) ,
    PRIMER_APELLIDO_MENSAJERO  VARCHAR2 (50) NOT NULL ,
    SEGUNDO_APELLIDO_MENSAJERO VARCHAR2 (50) ,
    ESTATUS_MENSAJERO          INTEGER NOT NULL ,
    VEHICULO_COD_VEHICULO      INTEGER NOT NULL
  ) ;
ALTER TABLE MENSAJEROS ADD CONSTRAINT MENSAJEROS_PK PRIMARY KEY ( COD_MENSAJERO ) ;


CREATE TABLE PAIS_EMPRESA_TRACKING
  (
    COD_PAIS_TRACKING     INTEGER NOT NULL ,
    DESCRIPCION_PAIS      VARCHAR2 (200) ,
    TRACKING_COD_TRACKING INTEGER NOT NULL
  ) ;
ALTER TABLE PAIS_EMPRESA_TRACKING ADD CONSTRAINT PAIS_EMPRESA_TRACKING_PK PRIMARY KEY ( COD_PAIS_TRACKING ) ;


CREATE TABLE PAQUETE
  (
    COD_PAQUETE                 INTEGER NOT NULL ,
    FECHA_ENVIO                 DATE NOT NULL ,
    FECHA_DESPACHO              DATE ,
    COD_VEHICULO                INTEGER NOT NULL ,
    NUMERO_HOJA_DESPACHO        INTEGER NOT NULL ,
    USUARIO_ENVIO_PAQUETE       VARCHAR2 (100) NOT NULL ,
    ESTATUS_PAQUETE             INTEGER NOT NULL ,
    ENVIOS_NUMERO_HOJA_DESPACHO INTEGER NOT NULL ,
    ENVIOS_COD_ENTREGA          INTEGER NOT NULL
  ) ;
ALTER TABLE PAQUETE ADD CONSTRAINT PAQUETE_PK PRIMARY KEY ( COD_PAQUETE ) ;


CREATE TABLE TIPO_VEHICULO
  (
    TIPO_VEHICULO        INTEGER NOT NULL ,
    DESCRI_TIPO_VEHICULO VARCHAR2 (100)
    --  ERROR: VARCHAR2 size not specified
    NOT NULL ,
    VEHICULO_COD_VEHICULO INTEGER NOT NULL
  ) ;
ALTER TABLE TIPO_VEHICULO ADD CONSTRAINT TIPO_VEHICULO_PK PRIMARY KEY ( TIPO_VEHICULO ) ;


CREATE TABLE TRACKING
  (
    COD_TRACKING                INTEGER NOT NULL ,
    COD_EMPRESA_TRACKING        INTEGER NOT NULL ,
    COD_PAIS_TRACKING           INTEGER NOT NULL ,
    COD_ESTATUS_TRACKING        INTEGER ,
    NUMERO_HOJA_DESPACHO        INTEGER ,
    ENVIOS_NUMERO_HOJA_DESPACHO INTEGER NOT NULL ,
    ENVIOS_COD_ENTREGA          INTEGER NOT NULL
  ) ;
ALTER TABLE TRACKING ADD CONSTRAINT TRACKING_PK PRIMARY KEY ( COD_TRACKING ) ;


CREATE TABLE VEHICULO
  (
    COD_VEHICULO        INTEGER NOT NULL ,
    TIPO_VEHICULO       INTEGER NOT NULL ,
    COD_PAQUETE         INTEGER NOT NULL ,
    COD_MENSAJERO       INTEGER NOT NULL ,
    ESTATUS_VEHICULO    INTEGER NOT NULL ,
    PAQUETE_COD_PAQUETE INTEGER NOT NULL
  ) ;
ALTER TABLE VEHICULO ADD CONSTRAINT VEHICULO_PK PRIMARY KEY ( COD_VEHICULO ) ;


--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE DIRECCIONES_ENTREGAS ADD CONSTRAINT DIREC_ENTRGS_ENTRG_FK FOREIGN KEY ( ENTREGA_COD_ENTREGA ) REFERENCES ENTREGA ( COD_ENTREGA ) ;

ALTER TABLE EMPRESA_TRACKING ADD CONSTRAINT EMPRESA_TRACKING_TRACKING_FK FOREIGN KEY ( TRACKING_COD_TRACKING ) REFERENCES TRACKING ( COD_TRACKING ) ;

ALTER TABLE ENTREGA ADD CONSTRAINT ENTREGA_ENVIOS_FK FOREIGN KEY ( ENVIOS_NUMERO_HOJA_DESPACHO, ENVIOS_COD_ENTREGA ) REFERENCES ENVIOS ( NUMERO_HOJA_DESPACHO, COD_ENTREGA ) ;

ALTER TABLE ENVIOS ADD CONSTRAINT ENVIOS_DESPACHO_FK FOREIGN KEY ( DESPACHO_COD_DESPACHO ) REFERENCES DESPACHO ( COD_DESPACHO ) ;

ALTER TABLE ESTATUS_DESPACHO ADD CONSTRAINT ESTATUS_DESPACHO_DESPACHO_FK FOREIGN KEY ( DESPACHO_COD_DESPACHO ) REFERENCES DESPACHO ( COD_DESPACHO ) ;

ALTER TABLE ESTATUS_ENTREGA ADD CONSTRAINT ESTATUS_ENTREGA_ENTREGA_FK FOREIGN KEY ( ENTREGA_COD_ENTREGA ) REFERENCES ENTREGA ( COD_ENTREGA ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ESTATUS_MENSAJERO ADD CONSTRAINT STATUS_MNSJR_MNSJRS_FK FOREIGN KEY ( MENSAJEROS_COD_MENSAJERO ) REFERENCES MENSAJEROS ( COD_MENSAJERO ) ;

ALTER TABLE ESTATUS_PAQUETE ADD CONSTRAINT ESTATUS_PAQUETE_PAQUETE_FK FOREIGN KEY ( PAQUETE_COD_PAQUETE ) REFERENCES PAQUETE ( COD_PAQUETE ) ;

ALTER TABLE ESTATUS_TRACKING ADD CONSTRAINT ESTATUS_TRACKING_TRACKING_FK FOREIGN KEY ( TRACKING_COD_TRACKING ) REFERENCES TRACKING ( COD_TRACKING ) ;

ALTER TABLE ESTATUS_VEHICULO ADD CONSTRAINT ESTATUS_VEHICULO_VEHICULO_FK FOREIGN KEY ( VEHICULO_COD_VEHICULO ) REFERENCES VEHICULO ( COD_VEHICULO ) ;

ALTER TABLE MENSAJEROS ADD CONSTRAINT MENSAJEROS_VEHICULO_FK FOREIGN KEY ( VEHICULO_COD_VEHICULO ) REFERENCES VEHICULO ( COD_VEHICULO ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE PAIS_EMPRESA_TRACKING ADD CONSTRAINT PAIS_EMPRE_TRCKNG_TRCKNG_FK FOREIGN KEY ( TRACKING_COD_TRACKING ) REFERENCES TRACKING ( COD_TRACKING ) ;

ALTER TABLE PAQUETE ADD CONSTRAINT PAQUETE_ENVIOS_FK FOREIGN KEY ( ENVIOS_NUMERO_HOJA_DESPACHO, ENVIOS_COD_ENTREGA ) REFERENCES ENVIOS ( NUMERO_HOJA_DESPACHO, COD_ENTREGA ) ;

ALTER TABLE TIPO_VEHICULO ADD CONSTRAINT TIPO_VEHI_VEHI_FK FOREIGN KEY ( VEHICULO_COD_VEHICULO ) REFERENCES VEHICULO ( COD_VEHICULO ) ;

ALTER TABLE TRACKING ADD CONSTRAINT TRACKING_ENVIOS_FK FOREIGN KEY ( ENVIOS_NUMERO_HOJA_DESPACHO, ENVIOS_COD_ENTREGA ) REFERENCES ENVIOS ( NUMERO_HOJA_DESPACHO, COD_ENTREGA ) ;

ALTER TABLE VEHICULO ADD CONSTRAINT VEHICULO_PAQUETE_FK FOREIGN KEY ( PAQUETE_COD_PAQUETE ) REFERENCES PAQUETE ( COD_PAQUETE ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             33
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   5
-- WARNINGS                                 0
